version: "3.6"
services:
  mongo:
    image: mongo
    container_name: Mnemosyne-vptis
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_toy_store:/data/db
volumes:
  mongo_toy_store:
